//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webescuela.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumnos
    {
        public int IdAlumno { get; set; }
        public string Apellidos { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public int Telefono { get; set; }
    }
}
